// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not supported in this project.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported in this project.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported in this project.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported in this project.',
        );
      default:
        throw UnsupportedError(
          'This platform is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQQmHJzdZfXUinlXaNq7uGZHytSpyi-a4',
    appId: '1:214737590735:android:1682a060f4680465069aba',
    messagingSenderId: '214737590735',
    projectId: 'medilink-36fad',
    storageBucket: 'medilink-36fad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4WMn8yKi5NzqPs0AIueynmZ7YRDT0mkc',
    appId: '1:214737590735:ios:4fa260dc3f6b9d8a069aba',
    messagingSenderId: '214737590735',
    projectId: 'medilink-36fad',
    storageBucket: 'medilink-36fad.firebasestorage.app',
    iosClientId: '214737590735-pei6t8vdmp4si86urhr9i6gb7k4th915.apps.googleusercontent.com',
    iosBundleId: 'com.example.medilinkApp',
  );

}