// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALyqgAmSfNIMX8NxCEU707gepAaf285c',
    appId: '1:893382002165:android:8a226b180c0203a9ed4cbc',
    messagingSenderId: '893382002165',
    projectId: 'medilink-e9a73',
    storageBucket: 'medilink-e9a73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mqp-H7VUe91bz4T1IC6JG21vJtu4IoE',
    appId: '1:893382002165:ios:f79f836e6b2ea325ed4cbc',
    messagingSenderId: '893382002165',
    projectId: 'medilink-e9a73',
    storageBucket: 'medilink-e9a73.firebasestorage.app',
    iosBundleId: 'com.example.medilinkApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoNAH99P8uZkXQmeLA6Y1Qr2a12SlC1R8',
    appId: '1:893382002165:web:78afc9fc876600beed4cbc',
    messagingSenderId: '893382002165',
    projectId: 'medilink-e9a73',
    authDomain: 'medilink-e9a73.firebaseapp.com',
    storageBucket: 'medilink-e9a73.firebasestorage.app',
    measurementId: 'G-34DVPN9029',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoNAH99P8uZkXQmeLA6Y1Qr2a12SlC1R8',
    appId: '1:893382002165:web:2eb9a7e9dcf757e7ed4cbc',
    messagingSenderId: '893382002165',
    projectId: 'medilink-e9a73',
    authDomain: 'medilink-e9a73.firebaseapp.com',
    storageBucket: 'medilink-e9a73.firebasestorage.app',
    measurementId: 'G-V71TSNKNCT',
  );

}