import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';
import 'screens/cart_screen.dart';
import 'screens/checkout_screen.dart';
import 'screens/orders_screen.dart';
import 'screens/last_order_screen.dart';

Future main() async {
WidgetsFlutterBinding.ensureInitialized();

// Initialize Firebase using the file generated by flutterfire configure
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
);

// Temporary: sign in anonymously so we have a uid
try {
await FirebaseAuth.instance.signInAnonymously();
} catch (e) {
// You can log or ignore during early development
}

runApp(const MedlinkApp());
}

class MedlinkApp extends StatelessWidget {
const MedlinkApp({super.key});

@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Medlink Pharmacy',
debugShowCheckedModeBanner: false,
theme: ThemeData(
colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF0E5AA6)),
scaffoldBackgroundColor: const Color(0xFFF2F7FB),
useMaterial3: false,
),
initialRoute: '/checkout',
routes: {
'/cart': (context) => CartScreen(),
'/checkout': (context) => CheckoutScreen(),
'/orders': (context) => OrdersScreen(),
'/last_order': (context) => LastOrderScreen(),
},
);
}
}